### ISSUE TITLE
DataArray/Coordinate Selection Panel

### ISSUE THREAD

**Issue by hdsingh** [intake/intake-gsoc-gui#14]
This panel would take a single xarray instance as input  which could be `DataSet` or `DataArray`. The "data input" is the xarray instance's structure: a tree of variables, sets of attributes and, for each variable, the associated coordinates. The coordinates fields may or may not have obvious interpretations as geographic location and time. The user can select the dataArray and coordinates from the displayed tree structure.

**Comment by hdsingh** [comment]
Refer https://github.com/intake/xrviz/pull/2

**Comment by hdsingh** [comment]
![Screenshot from 2019-06-07 00-59-43](https://user-images.githubusercontent.com/30382331/59122483-7f84c800-8978-11e9-8d13-c4d55a6f1127.png)

The multiselect widget on the left is the selection panel, which displays all the variables present in the Dataset or a single variable in case of DataArray. The variables which are coordinates have been annotated with the 📈 symbol. Upon selection of a variable, its information is updated in the adjoining description section.

**Comment by martindurant** [comment]
One thing missing here is a display of the attributes which are global the the whole dataset. That should be included on this panel, probably below the display you have so far.

**Comment by hdsingh** [comment]
The second table in description section shows the global attributes and they are always visible (do not change for a particular dataset) . I will mention about this in more detail in the [issue of Description panel](https://github.com/intake/intake-gsoc-gui/issues/15).

**Comment by martindurant** [comment]
Oh ok, got it. Later we may want to change its location, then.
