### ISSUE TITLE
Aggregations in the fields panel

### ISSUE THREAD

**Issue by hdsingh** [intake/intake-gsoc-gui#21]
Implement feature in the fields panel to have aggregations like `xr.mean()`.

**Comment by martindurant** [comment]
We will support the following options for dimensions which are not being used for plotting:
- max
- min
- mean
- stddev
- count (of non-nan)
- median
- select (this is currently the only option)

**Comment by hdsingh** [comment]
I have implemented these options:
- max
- min
- mean
- stddev
- median
 
on branch [add_aggregate](https://github.com/hdsingh/xrviz/tree/add_aggregate). Shall I wait for  [Pull Request #3](https://github.com/intake/xrviz/pull/3)  to merge before submitting this as PR?

I haven't been able to figure out what exactly to do with `count (of non-nan)`, how to find and create graph for it. Can you please elaborate this? For the example dataset I tried 
```
data.temp.count() - len(data.temp.isnull())
```
 but I think this is not correct approach. Is `count (of non-nan)` supposed to be number which we can simply display?

**Comment by martindurant** [comment]
Count along dimension "time"
```
(~ data.temp.isnull()).sum(dim='time')
```

**Comment by martindurant** [comment]
The operator `~` is bit- or element-wise NOT in python.

**Comment by hdsingh** [comment]
Thanks!

**Comment by hdsingh** [comment]
Refer https://github.com/intake/xrviz/pull/4

**Comment by hdsingh** [comment]
The user can aggregate along remaining dimensions (not selected in `x` and `y`). The option to create a `Select` widget or `Animate` is also present in case the user does not wish to apply any aggregation on the dimension.

![Screenshot from 2019-06-22 13-12-07](https://user-images.githubusercontent.com/30382331/59961066-786cc680-94ef-11e9-8f21-5b6d631925b7.png)
