### ISSUE TITLE
Style Panel

### ISSUE THREAD

**Issue by hdsingh** [intake/intake-gsoc-gui#22]
This panel will have options such as basemap and colormap to modify the appearance of plot.

**Comment by martindurant** [comment]
If there is a "geo" panel, then the choice of basemap might go there instead. The colourbar/colourmap certainly go here. We will see how many options we can support eventually.

**Comment by hdsingh** [comment]
Please refer [Style panel PR #13](https://github.com/intake/xrviz/pull/13).

**Comment by hdsingh** [comment]
The implementation of this panel is complete and has been merged.

![Screenshot from 2019-07-17 16-54-00](https://user-images.githubusercontent.com/30382331/61372033-bae9af00-a8b3-11e9-97a5-eb3b068ac941.png)
