### ISSUE TITLE
Series extraction.

### ISSUE THREAD

**Issue by hdsingh** [intake/intake-gsoc-gui#24]
This feature will allow the user to extract time series at a particular location. This would be similar to time series extraction implemented in [GreatLakes Dashboard](https://github.com/hdsingh/COAWST-ROMS_Dashboards/blob/master/GreatLakes_Dashboard.ipynb).

**Comment by martindurant** [comment]
Would prefer a little more specificity in these descriptions. If I may, something like:

"
To allow the user to click on the main 2D graphical output, and have a graph of a third dimension at that point appear in a separate, adjacent panel. Each click will produce a marker, and the line in the graph will have the same colour as that marker. Several lines can be over-plotted, and the dimension to use for the plotting will be chosen in the "fields" section of the interface.
"

**Comment by martindurant** [comment]
(note that the "third dimension" is not necessarily time, we need not be restricted to what ncview does)

**Comment by hdsingh** [comment]
> Would prefer a little more specificity in these descriptions. If I may, something like:

Thanks! Would specify more in the upcoming issue/descriptions.

**Comment by hdsingh** [comment]
Refer https://github.com/intake/xrviz/pull/27

**Comment by hdsingh** [comment]
This task is complete now. User can select the dimension to `extract along` in `Axes Panel`.

![Screenshot from 2019-07-21 00-00-36](https://user-images.githubusercontent.com/30382331/61731542-56d65780-ad99-11e9-9050-9118c372ea1e.png)
