### ISSUE TITLE
Tabular rearrangement

### ISSUE THREAD

**Issue by hdsingh** [intake/intake-gsoc-gui#26]
The tabs would be arranged in the following manner:

| Set Coords | Variables | Fields |
| ---------- |:---------:| ------:|

where:
`Set Coords` refers to tab having CrossSelector for setting coords,
`Variable` refers to the `Display` and `Describe Section`,
`Fields` refer to tab having `x`,`y` and `aggregations`.

The graph output area would always be visible.

This would be done after both [Aggregations PR#4](https://github.com/intake/xrviz/pull/4) and [Set reset coords PR #7](https://github.com/intake/xrviz/pull/7) are merged.

**Comment by martindurant** [comment]
Fields -> Axes

**Comment by hdsingh** [comment]
Please refer https://github.com/intake/xrviz/pull/12

**Comment by hdsingh** [comment]
This task is complete. This is how the interface appears now after rearrangement in tabs:
![Img](https://user-images.githubusercontent.com/30382331/60145827-e57ca680-97e4-11e9-8ee9-a5eeb97f5012.png)
