### ISSUE TITLE
The first evaluation for GSoC is complete

### ISSUE THREAD

**Issue by rsignell-usgs** [intake/intake-gsoc-gui#28]
![2019-06-25_9-43-01](https://user-images.githubusercontent.com/1872600/60103546-cbcc5800-972d-11e9-8aad-b8fb5b699840.png)

**Comment by rsignell-usgs** [comment]
cc @abburgess, @martindurant, @hdsingh

**Comment by martindurant** [comment]
Does that mean I need not do anything?

**Comment by rsignell-usgs** [comment]
@martindurant that is correct.  Only one mentor needs to fill out the survey.
