### ISSUE TITLE
Write a Blog post - "Beginning of my GSOC Journey"

### ISSUE THREAD

**Issue by hdsingh** [intake/intake-gsoc-gui#4]
This issue is also pre-coding task.

**Tasks:**
I have prepared my blog. The post would be available here: [Beginning of my GSOC Journey! -- Blog Posts | Hdsingh](https://hdsingh.github.io/pages/post1.html) .

**Comment by hdsingh** [comment]
The post is ready  [here](https://hdsingh.github.io/pages/post1.html).  It is also available on [Medium](https://medium.com/@hdsingh13/beginning-of-my-gsoc-journey-538e2e98851?source=friends_link&sk=cb7951de92db0cd905ed0defaf05c85c).

**Comment by martindurant** [comment]
Note that I work for Anaconda, inc - Continuum is the old name.

**Comment by hdsingh** [comment]
Corrected.

**Comment by martindurant** [comment]
Thanks

**Comment by rsignell-usgs** [comment]
Great job Harman!
