### ISSUE TITLE
Prepare quick basic implementation of data description section.

### ISSUE THREAD

**Issue by hdsingh** [intake/intake-gsoc-gui#5]
This issue is also pre-coding task.

**Task:**
Create a basic implementation of Data description as stated in my proposal.
![Screenshot from 2019-05-20 17-12-47](https://user-images.githubusercontent.com/30382331/58019284-c3777080-7b22-11e9-837b-45d4d09f8951.png)

**Comment by hdsingh** [comment]
This task has also been postponed and because it needs to be done according to the new design which would be discussed in the e-meet. However, I still tested my initial idea.

**Comment by hdsingh** [comment]
Just did a basic extraction/listing of coordinates and variable properties in [Description.ipynb](https://github.com/hdsingh/Dashboards/blob/master/06_Description.ipynb) which could be organised in any way (could be `hv.Table`).

**Comment by hdsingh** [comment]
Dataset properties:
![Screenshot from 2019-05-27 16-58-18](https://user-images.githubusercontent.com/30382331/58417126-7a369c00-80a1-11e9-93ba-d25bea7ca29b.png)

Variable properties:
![Screenshot from 2019-05-27 15-45-15](https://user-images.githubusercontent.com/30382331/58417140-828ed700-80a1-11e9-953c-f4c657e0bd08.png)

**Comment by hdsingh** [comment]
@rsignell-usgs @martindurant Sir, What are your thoughts regarding this initial approach?

**Comment by martindurant** [comment]
Displaying information in tables is OK, but in practice we might be better off formatting our own HTML for nicer output (e.g., xarray may well have a nice default representation soon, as dask.array does). However, the main problem is that some of these widgets will be used for *selecting*: the user wants to plot one of those variables, so they expect to be able to click on it. That means we need to be able to associate an event with the selection, which the hv.Table won't do.

Similar arguments can be made for other "attributes" which should be selectable, such as the coordinates associated with a given variable.

Aside from output-only areas, all control should probably be widgets from https://panel.pyviz.org/user_guide/Widgets.html
