### ISSUE TITLE
Create a list of milestones for the project

### ISSUE THREAD

**Issue by hdsingh** [intake/intake-gsoc-gui#6]
This issue is also pre-coding task.

It would be good to have a list of milestones for the tasks to be completed in the next three months, as discussed with the mentors in accordance with the proposal. Tasks would be added/modified upon further discussion with @rsignell-usgs, @martindurant  and community.

Shall we create this milestones list https://github.com/intake/xrviz here?

**Comment by hdsingh** [comment]
@martindurant @rsignell-usgs I have created issues for the blog posts to be written and documentation (https://github.com/intake/intake-gsoc-gui/issues/9 , https://github.com/intake/intake-gsoc-gui/issues/11, https://github.com/intake/intake-gsoc-gui/issues/12, https://github.com/intake/intake-gsoc-gui/issues/13). Additional issues and milestones would be created after the discussion.

**Comment by martindurant** [comment]
Ref https://github.com/intake/intake-gsoc-gui/milestones
