### ISSUE TITLE
Data Input section

### ISSUE THREAD

**Issue by hdsingh** [intake/intake-gsoc-gui#8]
**Task for Week 1**

Two options will be available for data input:
1. **Intake**
`intake.gui` would be used for data input into the dashboard.
2. **Remote URL**
Data would be loaded directly from the specified URL of a dataset.

`ADD data` button would initiate the process of data loading. The loaded data would be displayed in the next section.

![Screenshot from 2019-05-24 23-19-13](https://user-images.githubusercontent.com/30382331/58347410-7295ae00-7e7b-11e9-9519-49ea05fcff77.png)

**Comment by martindurant** [comment]
I think we should have a design meeting early next week before you go into too much detail or start writing any concrete code.

I believe that the interface should take an xarray instance as input (which may be metadata-only, in-memory or dask-backed) and not worry about connecting with intake or some URL. This way the interface need not depend on anything external. Then, the "data input" is the xarray instance's structure: a tree of variables, sets of attributes and, for each variable, the associated coordinates. The coordinates fields may or may not have obvious interpretations as geographic location and time.

**Comment by hdsingh** [comment]
There is no need for catalog input panel since `intake.gui` already has this functionality.
