### ISSUE TITLE
Blog Post - “XrViz: An interactive visualisation interface for Xarrays”

### ISSUE THREAD

**Issue by hdsingh** [intake/intake-gsoc-gui#9]
**Task for Week 1-2**

The post would be available on [Blog Posts | Hdsingh](https://hdsingh.github.io/pages/blog-posts.html).

**Comment by hdsingh** [comment]
As discussed in the meeting, this blog post would be about XrViz, since it has received less attention until now.

**Comment by hdsingh** [comment]
@rsignell-usgs @martindurant The blog post is ready [here](https://medium.com/@hdsingh13/xrviz-an-interactive-visualisation-interface-for-xarrays-9ecf8e325aa9?source=friends_link&sk=a01204364cf9d123dcb4e89277a4a6cf). It is also available on [my blog](https://hdsingh.github.io/pages/post2.html). Please have a look.

**Comment by hdsingh** [comment]
Since time for Phase I is about to get over and also this task is complete, I am closing this issue. Please feel free to leave your review here or let me know if anything needs to be changed in the blog.

**Comment by martindurant** [comment]
Yo maybe want to link to holoviz rather than pyviz (or both) because of the ongoing naming controversy.
